/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'Get Tickets': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'Get Ticket By ID': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'Pull Email': CronHandler<never>
  }
    
}